feat(cli): add `app delete` command
numerous-com/numerous-sdk pull request #13
Opened 2024-06-17 13:14 UTC by jfeodor

2024-06-18 14:09 UTC, moroderNumerous requested changes
<img src="https://media3.giphy.com/media/yJFeycRK2DB4c/giphy.gif"/>

2024-06-18 14:09 UTC, moroderNumerous commented on cli/internal/app/app_delete_test.go
> +	t.Run("given graphql error then it returns access denied error", func(t *testing.T) {
```suggestion
	t.Run("given graphql error then it returns given graphql error", func(t *testing.T) {
```

2024-06-18 14:09 UTC, moroderNumerous commented on cli/internal/app/app_delete_test.go
> +	t.Run("given graphql error then it returns access denied error", func(t *testing.T) {
I don't care what you change it to, It's just clear that's it's a leftover from a copy paste 😄

2024-06-18 14:13 UTC, jfeodor commented on cli/cmd/app/deletecmd/cmd.go
> +package deletecmd
`delete` is a reserved word so I had to find an alternative :smile:

2024-06-18 14:22 UTC, jfeodor commented on cli/cmd/app/deletecmd/cmd.go
> +	if err := Delete(cmd.Context(), service, appDir, slug, appName); err != nil {
nice idea :smile: 489ee60

2024-06-18 14:29 UTC, jfeodor commented on cli/cmd/app/appident/get_appidentifier.go
> +func GetAppIdentifier(appDir string, slug string, appName string) (string, string, error) {
Done in 412a84e

2024-06-19 07:46 UTC, moroderNumerous approved these changes

2024-06-19 07:57 UTC, merged